.PHONY: clean All

All:
	@echo "----------Building project:[ CinBomb - Debug ]----------"
	@cd "CinBomb" && "$(MAKE)" -f  "CinBomb.mk"
clean:
	@echo "----------Cleaning project:[ CinBomb - Debug ]----------"
	@cd "CinBomb" && "$(MAKE)" -f  "CinBomb.mk" clean
